export const WEBSITE_TOKEN_ENV_VAR = 'KREITZ_WEBDEV_WEBSITE_TOKEN';

export const RENDER_BLOCKING_TIMEOUT_MS = 3_000;

export const USER_ACTION_TIMEOUT_MS = 10_000;

export const CONTACT_FORM_NAME_MAX_LENGTH = 100;
export const CONTACT_FORM_MESSAGE_MAX_LENGTH = 5_000;
export const CONTACT_EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export const CONTACT_FORM_MIN_FILL_TIME_MS = 1_200;

export const CONTACT_FORM_JSON_BODY_LIMIT = '32kb';
